const ActionTypes = {
  CHANGE_THEME: 'CHANGE_THEME',
  SHOW_SIDEBAR: 'SHOW_SIDEBAR',
  HIDE_SIDEBAR: 'HIDE_SIDEBAR',
  COLLAPSE_SIDEBAR: 'COLLAPSE_SIDEBAR',
  UNCOLLAPSE_SIDEBAR: 'UNCOLLAPSE_SIDEBAR',
};

export default ActionTypes;
